name: Android CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      # نستخدم find للبحث عن ملف gradlew وتشغيله أينما كان
      run: find . -name "gradlew" -exec chmod +x {} +

    - name: Build with Gradle
      # سنقوم بالدخول للمجلد الذي يحتوي على gradlew تلقائياً وتنفيذ البناء
      run: |
        cd $(dirname $(find . -name "gradlew" | head -1))
        ./gradlew assembleDebug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AbuAlZahra-Child-App
        path: "**/*.apk" # سيبحث عن أي ملف APK تم إنتاجه ويرفعه
